name: Encrypt-Decrypt Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # tkinter is part of the standard library and does not need to be installed via pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Encrypt-Decrypt Application
      run: |
        # Use xvfb-run to run the Tkinter application in a virtual framebuffer
        xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python Code.py
