# This workflow will install Python dependencies and run the Encrypt-Decrypt application

name: Encrypt-Decrypt Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install base64 tkinter
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Encrypt-Decrypt Application
      run: |
        python Encrypt-Decrypt/Code.py
